"""
pyPreservica reporting API module definition

Reports about the content of a Preservica repository, generated by walking a folder
hierarchy (or the whole repository) and rendered as self-contained HTML pages.

The storage usage report sums the size of the bitstreams held by each asset and folder,
and renders the result as a radial "sunburst" chart in the style of the KDE Filelight
disk usage application.

The duplicate content report finds bitstreams which are held more than once, by
matching their size and fixity values.

author:     James Carr
licence:    Apache License 2.0

"""

import csv
import html
import json
import logging
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from typing import Union, Optional, Iterable, Callable, Generator, Any

from tqdm import tqdm

from pyPreservica.common import Folder, Asset, Entity, EntityType, RepresentationType, AuthenticatedAPI
from pyPreservica.entityAPI import EntityAPI

logger = logging.getLogger(__name__)



class StorageNode:
    """
    A node in the storage usage tree, either a folder or an asset.

    :param reference: The Preservica entity reference, ``None`` for the repository root.
    :param title: The entity title.
    :param entity_type: ``EntityType.FOLDER`` or ``EntityType.ASSET``.
    """

    def __init__(self, reference: Optional[str], title: str, entity_type: EntityType):
        self.reference = reference
        self.title = title
        self.entity_type = entity_type
        self.size: int = 0
        self.asset_count: int = 0
        self.bitstream_count: int = 0
        self.children: list["StorageNode"] = []

    @property
    def is_folder(self) -> bool:
        return self.entity_type == EntityType.FOLDER

    def to_dict(self) -> dict:
        """ Return the node, and all its children, as a dictionary suitable for JSON serialisation """
        node = {"ref": self.reference, "name": self.title, "type": "F" if self.is_folder else "A",
                "size": self.size, "assets": self.asset_count, "files": self.bitstream_count}
        if self.children:
            node["children"] = [c.to_dict() for c in self.children]
        return node

    @staticmethod
    def from_dict(data: dict) -> "StorageNode":
        """ Rebuild a storage tree from a dictionary created by to_dict() """
        node = StorageNode(data.get("ref"), data.get("name"),
                           EntityType.FOLDER if data.get("type") == "F" else EntityType.ASSET)
        node.size = int(data.get("size", 0))
        node.asset_count = int(data.get("assets", 0))
        node.bitstream_count = int(data.get("files", 0))
        node.children = [StorageNode.from_dict(c) for c in data.get("children", [])]
        return node

    def __str__(self):
        return f"{self.title} ({self.reference}): {human_size(self.size)}"

    def __repr__(self):
        return self.__str__()


def human_size(num_bytes: int) -> str:
    """
    Format a byte count as a human readable string using binary units, e.g. ``1.5 GiB``

    :param num_bytes: The number of bytes
    :return: The formatted string
    """
    size = float(num_bytes)
    for unit in ["B", "KiB", "MiB", "GiB", "TiB", "PiB"]:
        if abs(size) < 1024.0 or unit == "PiB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024.0
    return f"{size:.1f} PiB"


class RepositoryReport:
    """
    Base class for reports which walk a Preservica folder hierarchy and read the active
    bitstreams of each asset.

    Reading the bitstreams of an asset needs several API calls (representations, content objects,
    generations and bitstreams), so assets are processed in parallel using a pool of worker threads.

    :param client: An authenticated EntityAPI client.
    :param representation_types: The representation types to include.
    :param max_workers: The number of worker threads used to process assets in parallel.
    :param show_progress: Display a progress bar on the console while scanning.
    """

    def __init__(self, client: EntityAPI, representation_types: Iterable[RepresentationType],
                 max_workers: int = 4, show_progress: bool = True):
        self.client = client
        self.representation_types = set(representation_types)
        self.max_workers = max(1, int(max_workers))
        self.show_progress = show_progress
        self.scanned_at: Optional[datetime] = None
        self.server: Optional[str] = getattr(client, "server", None)
        self.tenant: Optional[str] = getattr(client, "tenant", None)

    def _active_bitstreams(self, asset: Asset) -> Generator[tuple[Any, Any, Any], None, None]:
        """
        Yield (representation, content object, bitstream) for each bitstream in the active generations
        of the selected representation types of an asset. Each bitstream is only returned once.
        """
        seen = set()
        for representation in self.client.representations(asset):
            if representation.rep_type not in self.representation_types:
                continue
            for content_object in self.client.content_objects(representation):
                for generation in self.client.generations(content_object):
                    if not generation.active:
                        continue
                    for bitstream in generation.bitstreams:
                        key = bitstream.content_url or (content_object.reference, bitstream.filename)
                        if key in seen:
                            continue
                        seen.add(key)
                        yield representation, content_object, bitstream

    def _for_each(self, items: list, function: Callable, description: str) -> list:
        """ Apply function to each item using the worker thread pool, returning the results in order """
        with tqdm(total=len(items), desc=description, unit=" assets", disable=not self.show_progress) as bar:
            if self.max_workers == 1:
                results = []
                for item in items:
                    results.append(function(item))
                    bar.update(1)
                return results
            with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
                results = []
                for result in executor.map(function, items):
                    results.append(result)
                    bar.update(1)
                return results

    def _resolve_folder(self, folder: Union[Folder, Entity, str, None]) -> Optional[Entity]:
        if isinstance(folder, str):
            return self.client.folder(folder)
        return folder

    def _report_header(self) -> dict:
        """ The fields common to the JSON form of every report """
        return {"server": self.server, "tenant": self.tenant,
                "scanned": self.scanned_at.isoformat(timespec="seconds") if self.scanned_at else None}

    def _load_header(self, data: dict):
        scanned = data.get("scanned")
        self.scanned_at = datetime.fromisoformat(scanned) if scanned else None
        self.server = data.get("server") or self.server
        self.tenant = data.get("tenant") or self.tenant

    def to_dict(self) -> dict:
        raise NotImplementedError

    def save_json(self, filename: str) -> str:
        """
        Save the scan results to a JSON file, so the report can be re-rendered without re-scanning.

        :param filename: The JSON file to write
        :return: The filename
        """
        with open(filename, "w", encoding="utf-8") as fd:
            json.dump(self.to_dict(), fd)
        return filename

    @staticmethod
    def _write_page(template: str, filename: str, title: str, data: dict) -> str:
        payload = json.dumps(data).replace("</", "<\\/")
        document = template.replace("__TITLE__", html.escape(title)).replace("__DATA__", payload)
        with open(filename, "w", encoding="utf-8") as fd:
            fd.write(document)
        return filename


class StorageUsageReport(RepositoryReport):
    """
    Calculate and visualise the storage used by a Preservica folder hierarchy.

    The report walks the folder tree using the Entity API, sums the size of the active
    generation bitstreams of every asset, and can render the result as an interactive
    HTML sunburst chart in the style of KDE Filelight.

    Sizing an asset needs several API calls (representations, content objects, generations
    and bitstreams), so assets are sized in parallel using a pool of worker threads.

    :param client: An authenticated EntityAPI client.
    :param representation_types: The representation types to include in the totals.
        Defaults to both Preservation and Access representations.
    :param max_workers: The number of worker threads used to size assets in parallel.
    :param show_progress: Display a progress bar on the console while scanning.
    """

    def __init__(self, client: EntityAPI,
                 representation_types: Iterable[RepresentationType] = (RepresentationType.Preservation,
                                                                        RepresentationType.Access),
                 max_workers: int = 4, show_progress: bool = True):
        super().__init__(client, representation_types, max_workers, show_progress)
        self.root: Optional[StorageNode] = None

    def _asset_size(self, asset: Asset) -> tuple[int, int]:
        """
        Return the total size in bytes and number of bitstreams of the active generations of an asset
        """
        total = 0
        count = 0
        for _, _, bitstream in self._active_bitstreams(asset):
            total += int(bitstream.length or 0)
            count += 1
        return total, count

    def _size_asset_node(self, node: StorageNode) -> StorageNode:
        try:
            node.size, node.bitstream_count = self._asset_size(Asset(node.reference, node.title))
        except Exception as e:
            logger.warning(f"Unable to calculate the size of asset {node.reference}: {e}")
        node.asset_count = 1
        return node

    def _build_tree(self, node: StorageNode, parent: Union[Folder, None], assets: list[StorageNode],
                    progress: Optional[Callable]):
        """ Walk the folder hierarchy, collecting asset nodes to be sized later """
        for entity in self.client.descendants(parent):
            child = StorageNode(entity.reference, entity.title, entity.entity_type)
            node.children.append(child)
            if entity.entity_type == EntityType.FOLDER:
                self._build_tree(child, entity, assets, progress)
            else:
                assets.append(child)
                if progress:
                    progress()

    @staticmethod
    def _roll_up(node: StorageNode):
        """ Sum the sizes of child nodes into their parent folders and sort children largest first """
        if not node.is_folder:
            return
        node.size = 0
        node.asset_count = 0
        node.bitstream_count = 0
        for child in node.children:
            StorageUsageReport._roll_up(child)
            node.size += child.size
            node.asset_count += child.asset_count
            node.bitstream_count += child.bitstream_count
        node.children.sort(key=lambda c: c.size, reverse=True)

    def scan(self, folder: Union[Folder, Entity, str, None] = None) -> StorageNode:
        """
        Scan a folder hierarchy and calculate the storage used by every folder and asset.

        :param folder: The folder (or folder reference) to start from, ``None`` for the whole repository.
        :return: The root StorageNode of the scanned tree.
        """
        folder = self._resolve_folder(folder)
        if folder is None:
            root = StorageNode(None, "Repository", EntityType.FOLDER)
        else:
            root = StorageNode(folder.reference, folder.title, EntityType.FOLDER)

        assets: list[StorageNode] = []
        with tqdm(desc="Scanning folders", unit=" assets", disable=not self.show_progress) as bar:
            self._build_tree(root, folder, assets, lambda: bar.update(1))

        self._for_each(assets, self._size_asset_node, "Sizing assets")

        self._roll_up(root)
        self.root = root
        self.scanned_at = datetime.now()
        return root

    def _require_scan(self):
        if self.root is None:
            raise RuntimeError("No scan results, call scan() or load_json() first")

    def to_dict(self) -> dict:
        """ Return the scan results as a dictionary """
        self._require_scan()
        return {**self._report_header(), "tree": self.root.to_dict()}

    def load_json(self, filename: str) -> StorageNode:
        """
        Load scan results previously saved with save_json()

        :param filename: The JSON file to read
        :return: The root StorageNode
        """
        with open(filename, "r", encoding="utf-8") as fd:
            data = json.load(fd)
        self.root = StorageNode.from_dict(data["tree"])
        self._load_header(data)
        return self.root

    def largest(self, limit: int = 10, entity_type: EntityType = EntityType.ASSET) -> list[StorageNode]:
        """
        Return the largest folders or assets in the scanned tree

        :param limit: The number of entities to return
        :param entity_type: Either EntityType.ASSET or EntityType.FOLDER
        :return: A list of StorageNode objects, largest first
        """
        self._require_scan()
        found = []
        stack = [self.root]
        while stack:
            node = stack.pop()
            if node.entity_type == entity_type and node is not self.root:
                found.append(node)
            stack.extend(node.children)
        found.sort(key=lambda n: n.size, reverse=True)
        return found[:limit]

    def _csv_rows(self, node: StorageNode, parent: Optional[StorageNode], path: list[str], depth: int,
                  entity_type: Optional[EntityType], max_depth: Optional[int]) -> Generator[list, None, None]:
        """ Yield a CSV row for a node and then its children, depth first, largest first """
        if max_depth is not None and depth > max_depth:
            return
        if entity_type is None or node.entity_type == entity_type:
            total = self.root.size
            yield ["Folder" if node.is_folder else "Asset", node.reference or "", node.title, " / ".join(path), depth,
                   node.size, human_size(node.size),
                   f"{100.0 * node.size / parent.size:.2f}" if parent is not None and parent.size else "",
                   f"{100.0 * node.size / total:.2f}" if total else "",
                   node.asset_count, node.bitstream_count]
        child_path = path + [node.title] if depth > 0 else path
        for child in node.children:
            yield from self._csv_rows(child, node, child_path, depth + 1, entity_type, max_depth)

    def save_csv(self, filename: str, entity_type: Optional[EntityType] = None, max_depth: Optional[int] = None) -> str:
        """
        Write one row per folder and asset to a CSV file, for use in a spreadsheet.

        Rows are written in tree order, each folder followed by its contents, largest first.
        The first row is the scanned folder (or the repository) at depth 0, with the overall totals.
        The folder path of each row is relative to the scanned folder.

        :param filename: The CSV file to write
        :param entity_type: Only write rows for EntityType.FOLDER or EntityType.ASSET, None for both
        :param max_depth: Only write rows down to this depth below the scanned folder, None for all levels
        :return: The filename
        """
        self._require_scan()
        with open(filename, "w", encoding="utf-8", newline="") as fd:
            writer = csv.writer(fd)
            writer.writerow(["type", "reference", "title", "folder_path", "depth", "size_bytes", "size",
                             "percent_of_parent", "percent_of_total", "assets", "files"])
            writer.writerows(self._csv_rows(self.root, None, [], 0, entity_type, max_depth))
        return filename

    def render_html(self, filename: str = "storage_usage.html", title: Optional[str] = None) -> str:
        """
        Render the scan results as a self-contained interactive HTML page containing a
        Filelight style sunburst chart and a sortable list of the folder contents.

        The page has no external dependencies and can be opened directly in a web browser.

        :param filename: The HTML file to write
        :param title: The page title, defaults to the name of the scanned folder
        :return: The filename
        """
        self._require_scan()
        return self._write_page(_HTML_TEMPLATE, filename, title or f"Storage usage: {self.root.title}", self.to_dict())


_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__</title>
<style>
:root { --bg:#eff0f1; --panel:#fff; --text:#232629; --muted:#7f8c8d; --border:#d1d3d5;
        --hover:#e3eef9; --sel:#3daee9; --bar:#dfe1e3; --stroke:#232629; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { --bg:#202326; --panel:#2a2e32; --text:#fcfcfc; --muted:#a1a9b1;
        --border:#3c4146; --hover:#33404d; --sel:#3daee9; --bar:#31363b; --stroke:#141618; }
}
* { box-sizing:border-box; }
html,body { margin:0; height:100%; }
body { background:var(--bg); color:var(--text); font:14px/1.35 "Noto Sans", "Segoe UI", system-ui, sans-serif;
       display:flex; flex-direction:column; }
header { display:flex; align-items:center; gap:4px; padding:6px 10px; background:var(--bar);
         border-bottom:1px solid var(--border); flex-wrap:wrap; }
header h1 { font-size:15px; font-weight:600; margin:0 auto 0 4px; white-space:nowrap; overflow:hidden;
            text-overflow:ellipsis; }
#source { display:flex; gap:6px 24px; padding:8px 14px; background:var(--panel); border-bottom:1px solid var(--border);
          flex-wrap:wrap; font-size:13px; }
#source:empty { display:none; }
#source div { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
#source span { color:var(--muted); margin-right:6px; }
#source b { font-weight:600; }
button { background:none; border:1px solid transparent; border-radius:4px; color:var(--text); font:inherit;
         padding:4px 10px; cursor:pointer; }
button:hover:not(:disabled) { background:var(--hover); border-color:var(--border); }
button:disabled { color:var(--muted); cursor:default; }
#crumbs { padding:6px 12px; font-size:13px; color:var(--muted); border-bottom:1px solid var(--border);
          background:var(--panel); white-space:nowrap; overflow-x:auto; }
#crumbs a { color:var(--text); cursor:pointer; text-decoration:none; }
#crumbs a:hover { text-decoration:underline; }
main { flex:1; display:flex; min-height:0; }
#list { width:340px; min-width:220px; background:var(--panel); border-right:1px solid var(--border);
        overflow-y:auto; }
.row { display:flex; gap:10px; padding:7px 12px; cursor:pointer; align-items:center; }
.row:hover, .row.hl { background:var(--hover); }
.sw { width:12px; height:12px; border-radius:2px; flex:none; border:1px solid var(--stroke); }
.row .n { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.row .s { font-size:12px; color:var(--muted); }
.row .txt { min-width:0; flex:1; }
.row .pct { font-size:12px; color:var(--muted); font-variant-numeric:tabular-nums; }
#chart { flex:1; display:flex; align-items:center; justify-content:center; min-width:0; position:relative; }
#chart svg { width:100%; height:100%; max-height:100%; }
#chart path { stroke:var(--stroke); stroke-width:0.6; cursor:pointer; }
#chart path:hover, #chart path.hl { filter:brightness(1.15) saturate(1.2); }
#centre { cursor:pointer; }
#tip { position:fixed; pointer-events:none; background:var(--panel); color:var(--text); border:1px solid var(--border);
       border-radius:4px; padding:6px 9px; font-size:13px; box-shadow:0 2px 8px rgba(0,0,0,.2); display:none;
       max-width:360px; z-index:5; }
#tip b { display:block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
#tip span { color:var(--muted); font-size:12px; }
footer { display:flex; justify-content:space-between; gap:12px; padding:5px 12px; background:var(--bar);
         border-top:1px solid var(--border); font-size:13px; flex-wrap:wrap; }
@media (max-width: 720px) {
  main { flex-direction:column-reverse; }
  #list { width:auto; border-right:none; border-top:1px solid var(--border); max-height:45vh; }
  #chart { min-height:55vh; }
}
</style>
</head>
<body>
<div id="source"></div>
<header>
  <h1 id="title"></h1>
  <button id="back" title="Back">&#8592; Back</button>
  <button id="fwd" title="Forward">Forward &#8594;</button>
  <button id="up" title="Up one level">&#8593; Up</button>
  <button id="home" title="Go to overview">&#8962; Overview</button>
</header>
<div id="crumbs"></div>
<main>
  <div id="list"></div>
  <div id="chart"><svg id="svg" viewBox="-340 -340 680 680" role="img" aria-label="Storage usage chart"></svg></div>
</main>
<footer><span id="status"></span><span id="counts"></span></footer>
<div id="tip"></div>
<script>
const DATA = __DATA__;
const RINGS = 5, INNER = 60, RING = 46, MIN_ANGLE = 0.012;
const svg = document.getElementById('svg'), list = document.getElementById('list'), tip = document.getElementById('tip');
const NS = 'http://www.w3.org/2000/svg';
let current = null, history = [], future = [];

(function link(n, p) { n.parent = p; (n.children || []).forEach(c => link(c, n)); })(DATA.tree, null);

function fmt(b) {
  const u = ['B','KiB','MiB','GiB','TiB','PiB']; let i = 0; b = Number(b);
  while (Math.abs(b) >= 1024 && i < u.length - 1) { b /= 1024; i++; }
  return i === 0 ? b + ' B' : b.toFixed(1) + ' ' + u[i];
}
function num(n) { return Number(n).toLocaleString(); }
function isFolder(n) { return n.type === 'F'; }

function colour(node, depth, midAngle) {
  if (node.grouped) return 'hsl(0,0%,82%)';
  if (!isFolder(node)) return `hsl(${Math.round(midAngle * 180 / Math.PI)},12%,${Math.min(88, 70 + depth * 3)}%)`;
  const hue = Math.round(midAngle * 180 / Math.PI);
  return `hsl(${hue},${Math.max(45, 80 - depth * 7)}%,${Math.min(78, 52 + depth * 6)}%)`;
}

function arc(r0, r1, a0, a1) {
  if (a1 - a0 >= 2 * Math.PI - 1e-6) a1 = a0 + 2 * Math.PI - 1e-4;
  const large = (a1 - a0) > Math.PI ? 1 : 0;
  const p = (r, a) => `${(r * Math.cos(a - Math.PI / 2)).toFixed(2)},${(r * Math.sin(a - Math.PI / 2)).toFixed(2)}`;
  return `M${p(r1, a0)}A${r1},${r1} 0 ${large} 1 ${p(r1, a1)}L${p(r0, a1)}A${r0},${r0} 0 ${large} 0 ${p(r0, a0)}Z`;
}

function segments(node, a0, a1, depth, out) {
  if (depth > RINGS || !node.children || node.size <= 0) return;
  let a = a0, small = [];
  for (const c of node.children) {
    const span = (a1 - a0) * (c.size / node.size);
    if (span < MIN_ANGLE) { small.push(c); continue; }
    out.push({node: c, a0: a, a1: a + span, depth});
    if (isFolder(c)) segments(c, a, a + span, depth + 1, out);
    a += span;
  }
  if (small.length) {
    const size = small.reduce((s, c) => s + c.size, 0), span = (a1 - a0) * (size / node.size);
    if (span > 0.002) out.push({node: {name: `${small.length} small items`, size, grouped: true, parent: node,
                                       assets: small.reduce((s, c) => s + c.assets, 0),
                                       files: small.reduce((s, c) => s + c.files, 0), type: 'G'},
                                a0: a, a1: a + span, depth});
  }
}

function el(tag, attrs, parent) {
  const e = document.createElementNS(NS, tag);
  for (const k in attrs) e.setAttribute(k, attrs[k]);
  if (parent) parent.appendChild(e);
  return e;
}

function showTip(ev, n) {
  const share = current.size ? (100 * n.size / current.size).toFixed(1) + '%' : '';
  tip.innerHTML = '';
  const b = document.createElement('b'); b.textContent = n.name || '(untitled)'; tip.appendChild(b);
  const s = document.createElement('span');
  s.textContent = `${fmt(n.size)} · ${share} · ${num(n.assets)} asset${n.assets === 1 ? '' : 's'}, ${num(n.files)} file${n.files === 1 ? '' : 's'}`;
  tip.appendChild(s);
  if (n.ref) { const r = document.createElement('span'); r.style.display = 'block'; r.textContent = n.ref; tip.appendChild(r); }
  tip.style.display = 'block';
  const x = Math.min(ev.clientX + 14, window.innerWidth - tip.offsetWidth - 8);
  const y = Math.min(ev.clientY + 14, window.innerHeight - tip.offsetHeight - 8);
  tip.style.left = x + 'px'; tip.style.top = y + 'px';
}
function hideTip() { tip.style.display = 'none'; }

function highlight(n, on) {
  document.querySelectorAll('[data-id]').forEach(e => { if (e._node === n) e.classList.toggle('hl', on); });
}

function activate(n) {
  if (!n || n.grouped) return;
  if (isFolder(n) && n.children && n.children.length) go(n);
}

function drawChart() {
  svg.innerHTML = '';
  const segs = []; segments(current, 0, 2 * Math.PI, 0, segs);
  let id = 0;
  for (const s of segs) {
    const mid = (s.a0 + s.a1) / 2;
    const p = el('path', {d: arc(INNER + s.depth * RING, INNER + (s.depth + 1) * RING - 1, s.a0, s.a1),
                          fill: colour(s.node, s.depth, mid), 'data-id': id++}, svg);
    p._node = s.node;
    p.addEventListener('mousemove', ev => showTip(ev, s.node));
    p.addEventListener('mouseenter', () => highlight(s.node, true));
    p.addEventListener('mouseleave', () => { hideTip(); highlight(s.node, false); });
    p.addEventListener('click', () => { hideTip(); activate(s.node); });
  }
  const c = el('circle', {r: INNER - 2, fill: 'var(--panel)', stroke: 'var(--border)', id: 'centre'}, svg);
  c.addEventListener('click', () => { if (current.parent) go(current.parent); });
  el('title', {}, c).textContent = current.parent ? 'Up one level' : current.name;
  const t = el('text', {'text-anchor': 'middle', 'dominant-baseline': 'middle', fill: 'var(--text)',
                        'font-size': 15, 'font-weight': 600, 'pointer-events': 'none'}, svg);
  t.textContent = fmt(current.size);
  if (!segs.length) {
    const e = el('text', {'text-anchor': 'middle', y: INNER + 30, fill: 'var(--muted)', 'font-size': 14}, svg);
    e.textContent = current.size ? 'Contents too small to display' : 'This folder is empty';
  }
}

function drawList() {
  list.innerHTML = '';
  const kids = current.children || [];
  if (!kids.length) {
    const d = document.createElement('div'); d.className = 'row'; d.style.cursor = 'default';
    d.textContent = 'No child folders or assets'; list.appendChild(d); return;
  }
  const n = kids.length;
  kids.forEach((k, i) => {
    const row = document.createElement('div'); row.className = 'row'; row.dataset.id = 'l' + i; row._node = k;
    const sw = document.createElement('span'); sw.className = 'sw';
    let a = 0; for (let j = 0; j < i; j++) a += kids[j].size;
    const mid = current.size ? 2 * Math.PI * (a + k.size / 2) / current.size : 0;
    sw.style.background = colour(k, 0, mid); row.appendChild(sw);
    const txt = document.createElement('div'); txt.className = 'txt';
    const nm = document.createElement('div'); nm.className = 'n';
    nm.textContent = (k.name || '(untitled)') + (isFolder(k) ? '/' : '');
    const sz = document.createElement('div'); sz.className = 's';
    sz.textContent = `${fmt(k.size)} · ${num(k.assets)} asset${k.assets === 1 ? '' : 's'}`;
    txt.appendChild(nm); txt.appendChild(sz); row.appendChild(txt);
    const pct = document.createElement('span'); pct.className = 'pct';
    pct.textContent = current.size ? (100 * k.size / current.size).toFixed(1) + '%' : '';
    row.appendChild(pct);
    row.title = k.ref || '';
    if (!isFolder(k)) row.style.cursor = 'default';
    row.addEventListener('mouseenter', () => highlight(k, true));
    row.addEventListener('mouseleave', () => highlight(k, false));
    row.addEventListener('click', () => activate(k));
    list.appendChild(row);
  });
}

function drawCrumbs() {
  const c = document.getElementById('crumbs'); c.innerHTML = '';
  const path = []; for (let n = current; n; n = n.parent) path.unshift(n);
  path.forEach((n, i) => {
    if (i) c.appendChild(document.createTextNode(' / '));
    const a = document.createElement('a'); a.textContent = n.name || '(untitled)';
    a.addEventListener('click', () => { if (n !== current) go(n); }); c.appendChild(a);
  });
}

function render() {
  document.getElementById('title').textContent = current.name || 'Repository';
  document.getElementById('back').disabled = !history.length;
  document.getElementById('fwd').disabled = !future.length;
  document.getElementById('up').disabled = !current.parent;
  document.getElementById('home').disabled = current === DATA.tree;
  document.getElementById('status').textContent =
    DATA.scanned ? 'Scanned ' + DATA.scanned.replace('T', ' ') : '';
  document.getElementById('counts').textContent =
    `${fmt(current.size)} · ${num(current.assets)} assets · ${num(current.files)} files`;
  drawCrumbs(); drawList(); drawChart();
}

function go(n, keepFuture) { if (n === current) return; history.push(current); if (!keepFuture) future = []; current = n; render(); }
document.getElementById('back').onclick = () => { if (history.length) { future.push(current); current = history.pop(); render(); } };
document.getElementById('fwd').onclick = () => { if (future.length) { history.push(current); current = future.pop(); render(); } };
document.getElementById('up').onclick = () => { if (current.parent) go(current.parent); };
document.getElementById('home').onclick = () => go(DATA.tree);
document.addEventListener('keydown', e => {
  if (e.key === 'Backspace' || (e.altKey && e.key === 'ArrowUp')) { e.preventDefault(); document.getElementById('up').click(); }
  else if (e.altKey && e.key === 'ArrowLeft') document.getElementById('back').click();
  else if (e.altKey && e.key === 'ArrowRight') document.getElementById('fwd').click();
});

(function source() {
  const box = document.getElementById('source');
  for (const [label, value] of [['Tenancy', DATA.tenant], ['Server', DATA.server]]) {
    if (!value) continue;
    const d = document.createElement('div'), l = document.createElement('span'), v = document.createElement('b');
    l.textContent = label; v.textContent = value; d.appendChild(l); d.appendChild(v); box.appendChild(d);
  }
})();

current = DATA.tree; render();
</script>
</body>
</html>
"""


# Preferred fixity algorithms, strongest first, used to choose which value to display for a group
FIXITY_PREFERENCE = ("SHA512", "SHA256", "SHA1", "MD5")


def _normalise_fixity(fixity: Optional[dict]) -> dict:
    """ Normalise fixity algorithm names (e.g. ``SHA-256`` to ``SHA256``) and values (lower case) """
    result = {}
    for algorithm, value in (fixity or {}).items():
        if algorithm and value:
            result[str(algorithm).upper().replace("-", "").strip()] = str(value).lower().strip()
    return result


def _preferred_algorithm(algorithms: Iterable[str]) -> Optional[str]:
    algorithms = set(algorithms)
    for algorithm in FIXITY_PREFERENCE:
        if algorithm in algorithms:
            return algorithm
    return sorted(algorithms)[0] if algorithms else None


class DuplicateFile:
    """
    A single copy of a bitstream which is held more than once.

    :param reference: The reference of the asset containing the bitstream.
    :param title: The title of the asset.
    :param path: The titles of the folders from the scanned folder down to the asset's parent.
    :param filename: The bitstream filename.
    :param size: The bitstream size in bytes.
    :param fixity: The bitstream fixity values as a dictionary of algorithm to value.
    :param representation: The representation type name, e.g. ``Preservation``.
    :param content_object: The reference of the content object containing the bitstream.
    """

    def __init__(self, reference: str, title: str, path: list[str], filename: str, size: int, fixity: dict,
                 representation: Optional[str] = None, content_object: Optional[str] = None):
        self.reference = reference
        self.title = title
        self.path = list(path)
        self.filename = filename
        self.size = int(size)
        self.fixity = _normalise_fixity(fixity)
        self.representation = representation
        self.content_object = content_object

    @property
    def folder_path(self) -> str:
        return " / ".join(self.path)

    def to_dict(self) -> dict:
        return {"ref": self.reference, "title": self.title, "path": self.path, "filename": self.filename,
                "size": self.size, "fixity": self.fixity, "rep": self.representation, "co": self.content_object}

    @staticmethod
    def from_dict(data: dict) -> "DuplicateFile":
        return DuplicateFile(data.get("ref"), data.get("title"), data.get("path", []), data.get("filename"),
                             data.get("size", 0), data.get("fixity", {}), data.get("rep"), data.get("co"))

    def __str__(self):
        return f"{self.filename} in {self.title} ({self.reference})"

    def __repr__(self):
        return self.__str__()


class DuplicateGroup:
    """
    A set of bitstreams with the same size and fixity, i.e. the same content held more than once.

    :param files: The copies of the bitstream.
    """

    def __init__(self, files: list[DuplicateFile]):
        self.files = files
        self.size = files[0].size if files else 0
        common = set(files[0].fixity) if files else set()
        for f in files[1:]:
            common &= set(f.fixity)
        algorithm = _preferred_algorithm(common) or (_preferred_algorithm(files[0].fixity) if files else None)
        self.algorithm: Optional[str] = algorithm
        self.fixity: Optional[str] = files[0].fixity.get(algorithm) if algorithm else None

    @property
    def copies(self) -> int:
        """ The number of copies of the bitstream """
        return len(self.files)

    @property
    def reclaimable(self) -> int:
        """ The number of bytes used by the extra copies, i.e. the space saved by keeping only one copy """
        return self.size * (self.copies - 1)

    @property
    def asset_count(self) -> int:
        """ The number of different assets holding a copy """
        return len({f.reference for f in self.files})

    def to_dict(self) -> dict:
        return {"size": self.size, "algorithm": self.algorithm, "fixity": self.fixity,
                "files": [f.to_dict() for f in self.files]}

    @staticmethod
    def from_dict(data: dict) -> "DuplicateGroup":
        return DuplicateGroup([DuplicateFile.from_dict(f) for f in data.get("files", [])])

    def __str__(self):
        return f"{self.copies} copies of {self.files[0].filename if self.files else ''} ({human_size(self.size)} each)"

    def __repr__(self):
        return self.__str__()


class DuplicateContentReport(RepositoryReport):
    """
    Find bitstreams which are held more than once in a Preservica folder hierarchy.

    The report walks the folder tree using the Entity API and reads the size and fixity values of the
    active generation bitstreams of every asset. Bitstreams with the same size and the same fixity value,
    for any fixity algorithm they have in common, are reported as duplicates.

    :param client: An authenticated EntityAPI client.
    :param representation_types: The representation types to include. Defaults to Preservation only.
    :param min_size: Ignore bitstreams smaller than this many bytes. The default of 1 ignores empty files,
        which would otherwise all be reported as duplicates of each other.
    :param max_workers: The number of worker threads used to read assets in parallel.
    :param show_progress: Display a progress bar on the console while scanning.
    """

    def __init__(self, client: EntityAPI,
                 representation_types: Iterable[RepresentationType] = (RepresentationType.Preservation,),
                 min_size: int = 1, max_workers: int = 4, show_progress: bool = True):
        super().__init__(client, representation_types, max_workers, show_progress)
        self.min_size = max(0, int(min_size))
        self.groups: Optional[list[DuplicateGroup]] = None
        self.scope: Optional[str] = None
        self.assets_scanned: int = 0
        self.assets_failed: int = 0
        self.files_scanned: int = 0
        self.bytes_scanned: int = 0
        self.files_without_fixity: int = 0

    def _walk(self, parent: Optional[Entity], path: list[str]) -> Generator[tuple[Asset, list[str]], None, None]:
        """ Yield each asset below a folder along with the titles of the folders above it """
        for entity in self.client.descendants(parent):
            if entity.entity_type == EntityType.FOLDER:
                yield from self._walk(entity, path + [entity.title])
            else:
                yield Asset(entity.reference, entity.title), path

    def _asset_files(self, item: tuple[Asset, list[str]]) -> Optional[list[DuplicateFile]]:
        asset, path = item
        try:
            files = []
            for representation, content_object, bitstream in self._active_bitstreams(asset):
                rep_type = getattr(representation, "rep_type", None)
                files.append(DuplicateFile(asset.reference, asset.title, path, bitstream.filename,
                                           int(bitstream.length or 0), bitstream.fixity,
                                           rep_type.value if rep_type is not None else None,
                                           getattr(content_object, "reference", None)))
            return files
        except Exception as e:
            logger.warning(f"Unable to read the bitstreams of asset {asset.reference}: {e}")
            return None

    @staticmethod
    def find_duplicates(files: Iterable[DuplicateFile], min_size: int = 1) -> list[DuplicateGroup]:
        """
        Group bitstreams with the same size and fixity value. Two bitstreams are duplicates if they share
        a value for any fixity algorithm, so files with different sets of algorithms can still be matched.

        :param files: The bitstreams to compare
        :param min_size: Ignore bitstreams smaller than this many bytes
        :return: The groups with more than one copy, largest reclaimable space first
        """
        files = [f for f in files if f.fixity and f.size >= min_size]
        parent = list(range(len(files)))

        def find(i: int) -> int:
            while parent[i] != i:
                parent[i] = parent[parent[i]]
                i = parent[i]
            return i

        first_seen = {}
        for i, f in enumerate(files):
            for algorithm, value in f.fixity.items():
                key = (f.size, algorithm, value)
                if key in first_seen:
                    parent[find(i)] = find(first_seen[key])
                else:
                    first_seen[key] = i

        buckets = defaultdict(list)
        for i, f in enumerate(files):
            buckets[find(i)].append(f)
        groups = [DuplicateGroup(b) for b in buckets.values() if len(b) > 1]
        groups.sort(key=lambda g: (g.reclaimable, g.copies), reverse=True)
        return groups

    def scan(self, folder: Union[Folder, Entity, str, None] = None) -> list[DuplicateGroup]:
        """
        Scan a folder hierarchy and find the bitstreams which are held more than once.

        :param folder: The folder (or folder reference) to start from, ``None`` for the whole repository.
        :return: The duplicate groups, largest reclaimable space first.
        """
        folder = self._resolve_folder(folder)
        self.scope = folder.title if folder is not None else "Repository"

        assets = []
        with tqdm(desc="Scanning folders", unit=" assets", disable=not self.show_progress) as bar:
            for item in self._walk(folder, []):
                assets.append(item)
                bar.update(1)

        results = self._for_each(assets, self._asset_files, "Reading fixity")

        files = []
        self.assets_failed = 0
        for result in results:
            if result is None:
                self.assets_failed += 1
            else:
                files.extend(result)
        self.assets_scanned = len(assets)
        self.files_scanned = len(files)
        self.bytes_scanned = sum(f.size for f in files)
        self.files_without_fixity = sum(1 for f in files if not f.fixity)
        self.groups = self.find_duplicates(files, self.min_size)
        self.scanned_at = datetime.now()
        return self.groups

    def _require_scan(self):
        if self.groups is None:
            raise RuntimeError("No scan results, call scan() or load_json() first")

    @property
    def duplicate_files(self) -> int:
        """ The number of extra copies, i.e. the number of files which could be removed """
        self._require_scan()
        return sum(g.copies - 1 for g in self.groups)

    @property
    def reclaimable(self) -> int:
        """ The total number of bytes used by extra copies """
        self._require_scan()
        return sum(g.reclaimable for g in self.groups)

    def largest(self, limit: int = 10) -> list[DuplicateGroup]:
        """
        Return the duplicate groups using the most space in extra copies

        :param limit: The number of groups to return
        :return: A list of DuplicateGroup objects
        """
        self._require_scan()
        return self.groups[:limit]

    def summary(self) -> dict:
        """ Return the scan totals as a dictionary """
        self._require_scan()
        return {"assets": self.assets_scanned, "failed": self.assets_failed, "files": self.files_scanned,
                "bytes": self.bytes_scanned, "no_fixity": self.files_without_fixity, "groups": len(self.groups),
                "duplicates": self.duplicate_files, "reclaimable": self.reclaimable, "min_size": self.min_size,
                "representations": sorted(r.value for r in self.representation_types)}

    def to_dict(self) -> dict:
        """ Return the scan results as a dictionary """
        self._require_scan()
        return {**self._report_header(), "scope": self.scope, "summary": self.summary(),
                "groups": [g.to_dict() for g in self.groups]}

    def load_json(self, filename: str) -> list[DuplicateGroup]:
        """
        Load scan results previously saved with save_json()

        :param filename: The JSON file to read
        :return: The duplicate groups
        """
        with open(filename, "r", encoding="utf-8") as fd:
            data = json.load(fd)
        self._load_header(data)
        self.scope = data.get("scope")
        summary = data.get("summary", {})
        self.assets_scanned = int(summary.get("assets", 0))
        self.assets_failed = int(summary.get("failed", 0))
        self.files_scanned = int(summary.get("files", 0))
        self.bytes_scanned = int(summary.get("bytes", 0))
        self.files_without_fixity = int(summary.get("no_fixity", 0))
        self.min_size = int(summary.get("min_size", self.min_size))
        if "representations" in summary:
            self.representation_types = {RepresentationType(r) for r in summary["representations"]}
        self.groups = [DuplicateGroup.from_dict(g) for g in data.get("groups", [])]
        return self.groups

    def save_csv(self, filename: str) -> str:
        """
        Write one row per duplicate bitstream to a CSV file, for use in a spreadsheet

        :param filename: The CSV file to write
        :return: The filename
        """
        self._require_scan()
        with open(filename, "w", encoding="utf-8", newline="") as fd:
            writer = csv.writer(fd)
            writer.writerow(["group", "copies", "size", "reclaimable", "algorithm", "fixity", "asset_reference",
                             "asset_title", "folder_path", "filename", "representation", "content_object"])
            for index, group in enumerate(self.groups, start=1):
                for f in group.files:
                    writer.writerow([index, group.copies, group.size, group.reclaimable, group.algorithm,
                                     group.fixity, f.reference, f.title, f.folder_path, f.filename,
                                     f.representation, f.content_object])
        return filename

    def render_html(self, filename: str = "duplicate_content.html", title: Optional[str] = None) -> str:
        """
        Render the scan results as a self-contained HTML page listing the duplicate bitstreams,
        with summary totals and a search box.

        The page has no external dependencies and can be opened directly in a web browser.

        :param filename: The HTML file to write
        :param title: The page title, defaults to the name of the scanned folder
        :return: The filename
        """
        self._require_scan()
        return self._write_page(_DUPLICATES_HTML_TEMPLATE, filename, title or f"Duplicate content: {self.scope}",
                                self.to_dict())


_DUPLICATES_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__</title>
<style>
:root { --bg:#eff0f1; --panel:#fff; --text:#232629; --muted:#6b7780; --border:#d1d3d5; --hover:#e3eef9;
        --bar:#dfe1e3; --accent:#1d6fa5; --warn:#b4531b; --chip:#e8ecef; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { --bg:#202326; --panel:#2a2e32; --text:#fcfcfc; --muted:#a1a9b1;
        --border:#3c4146; --hover:#33404d; --bar:#31363b; --accent:#5fb4eb; --warn:#f0a36b; --chip:#383d42; }
}
:root[data-theme="dark"] { --bg:#202326; --panel:#2a2e32; --text:#fcfcfc; --muted:#a1a9b1; --border:#3c4146;
        --hover:#33404d; --bar:#31363b; --accent:#5fb4eb; --warn:#f0a36b; --chip:#383d42; }
* { box-sizing:border-box; }
html,body { margin:0; }
body { background:var(--bg); color:var(--text); font:14px/1.4 "Noto Sans", "Segoe UI", system-ui, sans-serif; }
#source { display:flex; gap:6px 24px; padding:8px 16px; background:var(--panel); border-bottom:1px solid var(--border);
          flex-wrap:wrap; font-size:13px; }
#source:empty { display:none; }
#source div { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
#source span { color:var(--muted); margin-right:6px; }
#source b { font-weight:600; }
header { padding:14px 16px 4px; }
header h1 { font-size:20px; margin:0; font-weight:600; }
header p { margin:4px 0 0; color:var(--muted); font-size:13px; }
.wrap { max-width:1200px; margin:0 auto; padding:0 16px 24px; }
#tiles { display:grid; grid-template-columns:repeat(auto-fit, minmax(150px, 1fr)); gap:10px; margin:14px 0; }
.tile { background:var(--panel); border:1px solid var(--border); border-radius:6px; padding:10px 12px; }
.tile .v { font-size:22px; font-weight:600; font-variant-numeric:tabular-nums; }
.tile .l { color:var(--muted); font-size:12px; }
.tile.key .v { color:var(--warn); }
#notes { color:var(--muted); font-size:13px; margin:0 0 12px; }
#notes:empty { display:none; }
.tools { display:flex; gap:10px; flex-wrap:wrap; align-items:center; margin-bottom:12px; }
.tools input, .tools select { font:inherit; color:var(--text); background:var(--panel); border:1px solid var(--border);
          border-radius:4px; padding:6px 9px; }
.tools input { flex:1; min-width:200px; }
.tools .count { color:var(--muted); font-size:13px; }
details { background:var(--panel); border:1px solid var(--border); border-radius:6px; margin-bottom:8px; }
summary { list-style:none; cursor:pointer; padding:10px 12px; display:flex; gap:8px 14px; align-items:center;
          flex-wrap:wrap; }
summary::-webkit-details-marker { display:none; }
summary:hover { background:var(--hover); }
summary .caret { width:10px; color:var(--muted); transition:transform .15s; flex:none; }
details[open] summary .caret { transform:rotate(90deg); }
summary .name { font-weight:600; min-width:0; flex:1 1 220px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.chip { background:var(--chip); border-radius:10px; padding:1px 9px; font-size:12px; white-space:nowrap;
        font-variant-numeric:tabular-nums; }
.chip.warn { color:var(--warn); font-weight:600; }
.fix { font:12px ui-monospace, Consolas, monospace; color:var(--muted); padding:0 12px 8px 30px; overflow-wrap:anywhere; }
.copies { border-top:1px solid var(--border); }
.copy { display:grid; grid-template-columns:minmax(0,1.2fr) minmax(0,1.2fr) minmax(0,1.6fr) auto; gap:4px 14px;
        padding:8px 12px 8px 30px; border-bottom:1px solid var(--border); font-size:13px; }
.copy:last-child { border-bottom:none; }
.copy.head { color:var(--muted); font-size:12px; padding-top:6px; padding-bottom:6px; }
.copy div { min-width:0; overflow-wrap:anywhere; }
.copy .ref { font:12px ui-monospace, Consolas, monospace; color:var(--muted); display:block; }
.copy .rep { color:var(--muted); white-space:nowrap; }
.same { color:var(--accent); font-size:12px; }
#more { display:block; margin:12px auto; font:inherit; color:var(--text); background:var(--panel);
        border:1px solid var(--border); border-radius:4px; padding:6px 16px; cursor:pointer; }
#more:hover { background:var(--hover); }
.empty { background:var(--panel); border:1px solid var(--border); border-radius:6px; padding:24px; text-align:center;
         color:var(--muted); }
footer { color:var(--muted); font-size:12px; text-align:center; padding:8px 16px 20px; }
@media (max-width: 720px) {
  .copy { grid-template-columns:1fr; padding-left:14px; }
  .copy.head { display:none; }
  .fix { padding-left:14px; }
}
</style>
</head>
<body>
<div id="source"></div>
<header class="wrap"><h1 id="title"></h1><p id="scope"></p></header>
<div class="wrap">
  <div id="tiles"></div>
  <p id="notes"></p>
  <div class="tools">
    <input id="q" type="search" placeholder="Filter by filename, asset title, folder or reference" aria-label="Filter">
    <select id="sort" aria-label="Sort by">
      <option value="reclaimable">Largest reclaimable space</option>
      <option value="copies">Most copies</option>
      <option value="size">Largest file size</option>
      <option value="assets">Most assets</option>
    </select>
    <span class="count" id="count"></span>
  </div>
  <div id="groups"></div>
  <button id="more" hidden>Show more</button>
</div>
<footer id="footer"></footer>
<script>
const DATA = __DATA__;
const PAGE = 100;
let shown = PAGE, filtered = [];

function fmt(b) {
  const u = ['B','KiB','MiB','GiB','TiB','PiB']; let i = 0; b = Number(b);
  while (Math.abs(b) >= 1024 && i < u.length - 1) { b /= 1024; i++; }
  return i === 0 ? b + ' B' : b.toFixed(1) + ' ' + u[i];
}
function num(n) { return Number(n).toLocaleString(); }
function mk(tag, cls, text) {
  const e = document.createElement(tag); if (cls) e.className = cls; if (text !== undefined) e.textContent = text; return e;
}

DATA.groups.forEach(g => {
  g.copies = g.files.length;
  g.reclaimable = g.size * (g.copies - 1);
  g.assets = new Set(g.files.map(f => f.ref)).size;
  g.search = g.files.map(f => [f.filename, f.title, (f.path || []).join(' / '), f.ref].join(' ')).join(' ').toLowerCase()
             + ' ' + (g.fixity || '');
});

(function header() {
  const box = document.getElementById('source');
  for (const [label, value] of [['Tenancy', DATA.tenant], ['Server', DATA.server]]) {
    if (!value) continue;
    const d = mk('div'); d.appendChild(mk('span', '', label)); d.appendChild(mk('b', '', value)); box.appendChild(d);
  }
  const s = DATA.summary;
  document.getElementById('title').textContent = 'Duplicate content';
  document.getElementById('scope').textContent = 'Scope: ' + (DATA.scope || 'Repository') +
    ' · ' + (s.representations || []).join(' and ') + ' representations';
  const tiles = [
    ['Reclaimable space', fmt(s.reclaimable), true],
    ['Duplicate files', num(s.duplicates) + ' extra copies'],
    ['Duplicate groups', num(s.groups)],
    ['Files scanned', num(s.files) + ' · ' + fmt(s.bytes)],
    ['Assets scanned', num(s.assets)],
  ];
  const t = document.getElementById('tiles');
  for (const [label, value, key] of tiles) {
    const d = mk('div', 'tile' + (key ? ' key' : '')); d.appendChild(mk('div', 'v', value)); d.appendChild(mk('div', 'l', label));
    t.appendChild(d);
  }
  const notes = [];
  if (s.bytes) notes.push(`Extra copies use ${(100 * s.reclaimable / s.bytes).toFixed(2)}% of the scanned storage.`);
  if (s.no_fixity) notes.push(`${num(s.no_fixity)} files had no fixity value and could not be compared.`);
  if (s.failed) notes.push(`${num(s.failed)} assets could not be read.`);
  if (s.min_size > 1) notes.push(`Files smaller than ${fmt(s.min_size)} were ignored.`);
  else if (s.min_size === 1) notes.push('Empty files were ignored.');
  document.getElementById('notes').textContent = notes.join(' ');
  document.getElementById('footer').textContent = DATA.scanned ? 'Scanned ' + DATA.scanned.replace('T', ' ') : '';
})();

function groupCard(g) {
  const d = mk('details');
  const s = mk('summary');
  s.appendChild(mk('span', 'caret', '▶'));
  const names = new Set(g.files.map(f => f.filename));
  s.appendChild(mk('span', 'name', g.files[0].filename + (names.size > 1 ? ` (+${names.size - 1} other name${names.size > 2 ? 's' : ''})` : '')));
  s.appendChild(mk('span', 'chip', `${g.copies} copies`));
  s.appendChild(mk('span', 'chip', `${fmt(g.size)} each`));
  s.appendChild(mk('span', 'chip warn', `${fmt(g.reclaimable)} reclaimable`));
  if (g.assets === 1) s.appendChild(mk('span', 'same', 'all in one asset'));
  d.appendChild(s);
  d.addEventListener('toggle', () => {
    if (!d.open || d.dataset.filled) return;
    d.dataset.filled = '1';
    if (g.fixity) d.appendChild(mk('div', 'fix', `${g.algorithm}: ${g.fixity}`));
    const list = mk('div', 'copies');
    const head = mk('div', 'copy head');
    ['Filename', 'Asset', 'Folder', 'Representation'].forEach(h => head.appendChild(mk('div', '', h)));
    list.appendChild(head);
    for (const f of g.files) {
      const row = mk('div', 'copy');
      row.appendChild(mk('div', '', f.filename || ''));
      const a = mk('div', '', f.title || '(untitled)'); a.appendChild(mk('span', 'ref', f.ref || '')); row.appendChild(a);
      row.appendChild(mk('div', '', (f.path || []).join(' / ') || '(top level)'));
      row.appendChild(mk('div', 'rep', f.rep || ''));
      list.appendChild(row);
    }
    d.appendChild(list);
  });
  return d;
}

function render() {
  const q = document.getElementById('q').value.trim().toLowerCase();
  const key = document.getElementById('sort').value;
  filtered = DATA.groups.filter(g => !q || g.search.includes(q));
  filtered.sort((a, b) => b[key] - a[key] || b.reclaimable - a.reclaimable);
  const box = document.getElementById('groups'); box.innerHTML = '';
  if (!DATA.groups.length) {
    box.appendChild(mk('div', 'empty', 'No duplicate content was found.'));
  } else if (!filtered.length) {
    box.appendChild(mk('div', 'empty', 'No duplicate groups match the filter.'));
  }
  filtered.slice(0, shown).forEach(g => box.appendChild(groupCard(g)));
  const more = document.getElementById('more');
  more.hidden = filtered.length <= shown;
  more.textContent = `Show more (${num(filtered.length - shown)} remaining)`;
  const reclaim = filtered.reduce((s, g) => s + g.reclaimable, 0);
  document.getElementById('count').textContent =
    `${num(filtered.length)} group${filtered.length === 1 ? '' : 's'} · ${fmt(reclaim)} reclaimable`;
}

document.getElementById('q').addEventListener('input', () => { shown = PAGE; render(); });
document.getElementById('sort').addEventListener('change', () => { shown = PAGE; render(); });
document.getElementById('more').addEventListener('click', () => { shown += PAGE; render(); });
render();
</script>
</body>
</html>
"""


class ReportingAPI(AuthenticatedAPI):
    """
    API for generating reports about the content of a Preservica repository.

    Authenticates in the same way as the other pyPreservica API classes, using explicit arguments,
    environment variables or a ``credentials.properties`` file.

    Reports which need to walk the repository use an ``EntityAPI`` client, which is created with the
    same credentials the first time it is needed and then reused for later reports.
    """

    def __init__(self, username: str|None = None, password: str|None = None, tenant: str|None = None, server: str|None = None,
                 use_shared_secret: bool = False, two_fa_secret_key: str|None = None,
                 protocol: str = "https", request_hook: Callable|None = None, credentials_path: str = 'credentials.properties'):
        self.request_hook = request_hook
        self.credentials_path = credentials_path
        self._entity_client: Optional[EntityAPI] = None

        super().__init__(username, password, tenant, server, use_shared_secret, two_fa_secret_key,
                         protocol, request_hook, credentials_path)

    @property
    def entity_client(self) -> EntityAPI:
        """
        The EntityAPI client used to walk the repository, created on first use with the same credentials
        """
        if self._entity_client is None:
            self._entity_client = EntityAPI(username=self.username, password=self.password, server=self.server,
                                            tenant=self.tenant, use_shared_secret=self.shared_secret,
                                            two_fa_secret_key=self.two_fa_secret_key, protocol=self.protocol,
                                            request_hook=self.request_hook, credentials_path=self.credentials_path)
        return self._entity_client

    def storage_usage_report(self, folder: Union[Folder, Entity, str, None] = None,
                             filename: str = "storage_usage.html",
                             representation_types: Iterable[RepresentationType] = (RepresentationType.Preservation,
                                                                                    RepresentationType.Access),
                             max_workers: int = 4, show_progress: bool = True) -> StorageUsageReport:
        """
        Scan a folder (or the whole repository when folder is None) and write a Filelight
        style storage usage HTML report.

        :param folder: The folder or folder reference to scan, None for the repository root
        :param filename: The HTML file to write
        :param representation_types: The representation types to include in the totals.
            Defaults to both Preservation and Access representations.
        :param max_workers: The number of worker threads used to size assets
        :param show_progress: Display progress bars on the console
        :return: The StorageUsageReport, which can be used to save the results as CSV or JSON
        """
        report = StorageUsageReport(self.entity_client, representation_types=representation_types,
                                    max_workers=max_workers, show_progress=show_progress)
        report.scan(folder)
        report.render_html(filename)
        return report

    def duplicate_content_report(self, folder: Union[Folder, Entity, str, None] = None,
                                 filename: str = "duplicate_content.html",
                                 representation_types: Iterable[RepresentationType] = (RepresentationType.Preservation,),
                                 min_size: int = 1, max_workers: int = 4,
                                 show_progress: bool = True) -> DuplicateContentReport:
        """
        Scan a folder (or the whole repository when folder is None) for bitstreams which are held
        more than once, by matching their size and fixity values, and write an HTML report.

        :param folder: The folder or folder reference to scan, None for the repository root
        :param filename: The HTML file to write
        :param representation_types: The representation types to include. Defaults to Preservation only.
        :param min_size: Ignore bitstreams smaller than this many bytes, the default of 1 ignores empty files
        :param max_workers: The number of worker threads used to read assets
        :param show_progress: Display progress bars on the console
        :return: The DuplicateContentReport, which can be used to save the results as CSV or JSON
        """
        report = DuplicateContentReport(self.entity_client, representation_types=representation_types,
                                        min_size=min_size, max_workers=max_workers, show_progress=show_progress)
        report.scan(folder)
        report.render_html(filename)
        return report
